kind: ConfigMap
apiVersion: v1
metadata:
  name: as3-configmap
  namespace: hello-world
  labels:
    f5type: virtual-server
    as3: "true"  # set to true to process this configMap. For staging set to false.
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
          "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
          "partition1": {
            "class": "Tenant",
              "app1": {
                "class": "Application",
                "app1_vs": {
                  "class": "Service_HTTP",
                  "virtualAddresses": [
                    "10.0.2.101"
                   ],
                  "persistenceMethods":[
                    "destination-address"
                  ],
                  "pool": "app1_pool"
                },
                "app1_pool": {
                   "class": "Pool",
                   "monitors": [
                      "http"
                   ],
                   "members": [{
                      "servicePort": 80,
                      "serverAddresses": []
                   }]
                }
             }
          }
      }
    }
