kind: ConfigMap
apiVersion: v1
metadata:
  name: https-example
  namespace: hello-world
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.13.0",
          "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
          "partition1": {
            "class": "Tenant",
             "app1": {
               "class": "Application",
                 "template": "https",
                   "serviceMain": {
                       "class": "Service_HTTPS",
                       "virtualAddresses": [
                          "10.0.2.100",
                          "10.0.2.101"
                        ],
                        "persistenceMethods":[
                            "destination-address"
                        ],
                        "pool": "app1_pool",
                        "serverTLS": "frontside"
                    },
                    "app1_pool": {
                      "class": "Pool",
                      "monitors": [
                        "http"
                      ],
                      "members": [
                        {
                          "servicePort": 80,
                          "serverAddresses": []
                        }
                      ]
                    },
                    "frontside": {
                      "class": "TLS_Server",
                      "certificates": [
                        {
                          "certificate": "webcert"
                        }
                      ]
                    },
                    "webcert": {
                      "class": "Certificate",
                      "certificate": {"bigip":"/Common/default.crt"},
                      "privateKey": {"bigip":"/Common/default.key"}
                    }
                }
            }
        }
    }
